name: better_player_example
description: Better Player example usage app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  #better_player: any
  better_player:
    path: ../
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  visibility_detector: ^0.1.5
  path_provider: ^1.6.28
  collection: ^1.14.13

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/
  uses-material-design: true